create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  main_numbers jsonb not null,
  bonus_number int not null check (bonus_number between 1 and 45),
  created_at timestamptz not null default now()
);

alter table public.lotto_draws enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'lotto_draws'
      and policyname = 'Public can read lotto draws'
  ) then
    create policy "Public can read lotto draws"
    on public.lotto_draws
    for select
    using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'lotto_draws'
      and policyname = 'Public can insert lotto draws'
  ) then
    create policy "Public can insert lotto draws"
    on public.lotto_draws
    for insert
    with check (true);
  end if;
end
$$;
